import "./globals.css";
import { Inter } from "next/font/google";
import LoginState from "../context/loginContext/loginState";
import CatalogueState from "../context/catalogueContext/catalogueState";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster />
        <LoginState>
          <CatalogueState>
            {children}
          </CatalogueState>
        </LoginState>
      </body>
    </html>
  );
}
